### ISSUE TITLE
What are the units for each measure?

### ISSUE THREAD

**Issue by nicholaspoggioli** [LinkNLearn/homedata#10]
What is the unit of measure for warm_up?

What is the unit of measure for voc?

What is the unit of measure for co2?

**Comment by pwdel** [comment]
I did get some more information from the guy who provided the data.  I will upload what he gave me, which includes an illustration.  If I don't have the units, I will ask for those.

**Comment by pwdel** [comment]
HTU21D:
https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FHPC199_6%7FA6%7Fpdf%7FEnglish%7FENG_DS_HPC199_6_A6.pdf%7FCAT-HSC0004

**Comment by pwdel** [comment]
DHT22:
https://www.sparkfun.com/datasheets/Sensors/Temperature/DHT22.pdf

**Comment by pwdel** [comment]
DS18B20:
https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf

**Comment by nicholaspoggioli** [comment]
Information on health, indoor air quality, and TVOCs: https://iaqscience.lbl.gov/voc-intro

**Comment by nicholaspoggioli** [comment]
I searched the docs for the HTU21D, DHT22, and DS18B20 for 'voc' and did not get any hits. The voc measure is linked to the main floor in the data. DHT22 is listed as the main floor sensor in the README. 

Is there another sensor that might be there?

**Comment by pwdel** [comment]
Hello Nicholas, yes, very astute - I don't see that either.  I posted what I have on the GitHub readme just now and sent the link over to the homeowner who owns all of the sensors and asked if we could have all of the exact part numbers on all of the data including the tVOC and what kind of phone and app he used to monitor activity.

What I'm learning here is that there is a lot of contextual research that needs to be done and the end point data collection may not have all of the data in a perfect package for the data scientist(s) when you first start out.  I think this may be abstractly referred to as, "cleaning," however we could maybe more precisely refer to this as the, "contextual gathering" stage of "cleaning."

Yes you are absolutely right there are other sensors involved, we need to find out precisely what they are and their operating parameters from a statistical sampling perspective because we don't know 100% what we are looking for yet.  Knowing the, "error rate" of these things will be important to visualize and explore what's going on.  E.g., it's not likely, but perhaps the error rate could be rated at >20%...then any hypothesis we form would need to take this into account.

**Comment by pwdel** [comment]
Whoops, didn't mean to close, reopening.
